? ''
: default_value
clear_zone_override:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    entity_id:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.066119'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        entity:
          ? ''
          : default_value
          domain: climate
          integration: evohome
          metadata:
            last_updated: '2023-11-16T10:18:23.066119'
            version: '1.0'
        metadata:
          last_updated: '2023-11-16T10:18:23.066119'
          version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.066119'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:23.066119'
    version: '1.0'
metadata:
  last_updated: '2023-11-16T10:18:23.066119'
  version: '1.0'
refresh_system: null
reset_system: null
set_system_mode:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    duration:
      ? ''
      : default_value
      example: '{"hours": 18}'
      metadata:
        last_updated: '2023-11-16T10:18:23.066119'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.066119'
          version: '1.0'
        object: null
    metadata:
      last_updated: '2023-11-16T10:18:23.066119'
      version: '1.0'
    mode:
      ? ''
      : default_value
      example: Away
      metadata:
        last_updated: '2023-11-16T10:18:23.066119'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.066119'
          version: '1.0'
        select:
          ? ''
          : default_value
          metadata:
            last_updated: '2023-11-16T10:18:23.066119'
            version: '1.0'
          options:
          - Auto
          - AutoWithEco
          - Away
          - Custom
          - DayOff
          - HeatingOff
    period:
      ? ''
      : default_value
      example: '{"days": 28}'
      metadata:
        last_updated: '2023-11-16T10:18:23.066119'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.066119'
          version: '1.0'
        object: null
  metadata:
    last_updated: '2023-11-16T10:18:23.066119'
    version: '1.0'
set_zone_override:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    duration:
      ? ''
      : default_value
      example: '{"minutes": 135}'
      metadata:
        last_updated: '2023-11-16T10:18:23.066119'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.066119'
          version: '1.0'
        object: null
    entity_id:
      ? ''
      : default_value
      example: climate.bathroom
      metadata:
        last_updated: '2023-11-16T10:18:23.066119'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        entity:
          ? ''
          : default_value
          domain: climate
          integration: evohome
          metadata:
            last_updated: '2023-11-16T10:18:23.066119'
            version: '1.0'
        metadata:
          last_updated: '2023-11-16T10:18:23.066119'
          version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.066119'
      version: '1.0'
    setpoint:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.066119'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.066119'
          version: '1.0'
        number:
          ? ''
          : default_value
          max: 35.0
          metadata:
            last_updated: '2023-11-16T10:18:23.066119'
            version: '1.0'
          min: 4.0
          step: 0.1
  metadata:
    last_updated: '2023-11-16T10:18:23.066119'
    version: '1.0'
