? ''
: default_value
metadata:
  last_updated: '2023-11-16T10:18:23.557239'
  version: '1.0'
reload: null
remove:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:23.557239'
      version: '1.0'
    object_id:
      ? ''
      : default_value
      example: test_group
      metadata:
        last_updated: '2023-11-16T10:18:23.557239'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.557239'
          version: '1.0'
        object: null
  metadata:
    last_updated: '2023-11-16T10:18:23.557239'
    version: '1.0'
set:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    add_entities:
      ? ''
      : default_value
      example: domain.entity_id1, domain.entity_id2
      metadata:
        last_updated: '2023-11-16T10:18:23.557239'
        version: '1.0'
      selector:
        ? ''
        : default_value
        entity:
          ? ''
          : default_value
          metadata:
            last_updated: '2023-11-16T10:18:23.557239'
            version: '1.0'
          multiple: true
        metadata:
          last_updated: '2023-11-16T10:18:23.557239'
          version: '1.0'
    all:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.557239'
        version: '1.0'
      selector:
        ? ''
        : default_value
        boolean: null
        metadata:
          last_updated: '2023-11-16T10:18:23.557239'
          version: '1.0'
    entities:
      ? ''
      : default_value
      example: domain.entity_id1, domain.entity_id2
      metadata:
        last_updated: '2023-11-16T10:18:23.557239'
        version: '1.0'
      selector:
        ? ''
        : default_value
        entity:
          ? ''
          : default_value
          metadata:
            last_updated: '2023-11-16T10:18:23.557239'
            version: '1.0'
          multiple: true
        metadata:
          last_updated: '2023-11-16T10:18:23.557239'
          version: '1.0'
    icon:
      ? ''
      : default_value
      example: mdi:camera
      metadata:
        last_updated: '2023-11-16T10:18:23.557239'
        version: '1.0'
      selector:
        ? ''
        : default_value
        icon: null
        metadata:
          last_updated: '2023-11-16T10:18:23.557239'
          version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.557239'
      version: '1.0'
    name:
      ? ''
      : default_value
      example: My test group
      metadata:
        last_updated: '2023-11-16T10:18:23.557239'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.557239'
          version: '1.0'
        text: null
    object_id:
      ? ''
      : default_value
      example: test_group
      metadata:
        last_updated: '2023-11-16T10:18:23.557239'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.557239'
          version: '1.0'
        text: null
    remove_entities:
      ? ''
      : default_value
      example: domain.entity_id1, domain.entity_id2
      metadata:
        last_updated: '2023-11-16T10:18:23.557239'
        version: '1.0'
      selector:
        ? ''
        : default_value
        entity:
          ? ''
          : default_value
          metadata:
            last_updated: '2023-11-16T10:18:23.557239'
            version: '1.0'
          multiple: true
        metadata:
          last_updated: '2023-11-16T10:18:23.557239'
          version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:23.557239'
    version: '1.0'
