? ''
: default_value
create_event:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    description:
      ? ''
      : default_value
      example: Meeting to provide technical review for 'Phoenix' design.
      metadata:
        last_updated: '2023-11-16T10:18:22.397533'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.397533'
          version: '1.0'
        text: null
    end_date:
      ? ''
      : default_value
      example: '2022-03-23'
      metadata:
        last_updated: '2023-11-16T10:18:22.397533'
        version: '1.0'
      selector:
        ? ''
        : default_value
        date: null
        metadata:
          last_updated: '2023-11-16T10:18:22.397533'
          version: '1.0'
    end_date_time:
      ? ''
      : default_value
      example: '2022-03-22 22:00:00'
      metadata:
        last_updated: '2023-11-16T10:18:22.397533'
        version: '1.0'
      selector:
        ? ''
        : default_value
        datetime: null
        metadata:
          last_updated: '2023-11-16T10:18:22.397533'
          version: '1.0'
    in:
      ? ''
      : default_value
      example: '{"days": 2} or {"weeks": 2}'
      metadata:
        last_updated: '2023-11-16T10:18:22.397533'
        version: '1.0'
    location:
      ? ''
      : default_value
      example: Conference Room - F123, Bldg. 002
      metadata:
        last_updated: '2023-11-16T10:18:22.397533'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.397533'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.397533'
      version: '1.0'
    start_date:
      ? ''
      : default_value
      example: '2022-03-22'
      metadata:
        last_updated: '2023-11-16T10:18:22.397533'
        version: '1.0'
      selector:
        ? ''
        : default_value
        date: null
        metadata:
          last_updated: '2023-11-16T10:18:22.397533'
          version: '1.0'
    start_date_time:
      ? ''
      : default_value
      example: '2022-03-22 20:00:00'
      metadata:
        last_updated: '2023-11-16T10:18:22.397533'
        version: '1.0'
      selector:
        ? ''
        : default_value
        datetime: null
        metadata:
          last_updated: '2023-11-16T10:18:22.397533'
          version: '1.0'
    summary:
      ? ''
      : default_value
      example: Department Party
      metadata:
        last_updated: '2023-11-16T10:18:22.397533'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.397533'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:22.397533'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: calendar
      metadata:
        last_updated: '2023-11-16T10:18:22.397533'
        version: '1.0'
      supported_features:
      - calendar.CalendarEntityFeature.CREATE_EVENT
    metadata:
      last_updated: '2023-11-16T10:18:22.397533'
      version: '1.0'
list_events:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    duration:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:22.397533'
        version: '1.0'
      selector:
        ? ''
        : default_value
        duration: null
        metadata:
          last_updated: '2023-11-16T10:18:22.397533'
          version: '1.0'
    end_date_time:
      ? ''
      : default_value
      example: '2022-03-22 22:00:00'
      metadata:
        last_updated: '2023-11-16T10:18:22.397533'
        version: '1.0'
      selector:
        ? ''
        : default_value
        datetime: null
        metadata:
          last_updated: '2023-11-16T10:18:22.397533'
          version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.397533'
      version: '1.0'
    start_date_time:
      ? ''
      : default_value
      example: '2022-03-22 20:00:00'
      metadata:
        last_updated: '2023-11-16T10:18:22.397533'
        version: '1.0'
      selector:
        ? ''
        : default_value
        datetime: null
        metadata:
          last_updated: '2023-11-16T10:18:22.397533'
          version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.397533'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: calendar
      metadata:
        last_updated: '2023-11-16T10:18:22.397533'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.397533'
      version: '1.0'
metadata:
  last_updated: '2023-11-16T10:18:22.397533'
  version: '1.0'
