? ''
: default_value
add_url:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:22.006933'
      version: '1.0'
    name:
      ? ''
      : default_value
      example: Example
      metadata:
        last_updated: '2023-11-16T10:18:22.006933'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.006933'
          version: '1.0'
        text: null
    url:
      ? ''
      : default_value
      example: https://www.example.com/filter/1.txt
      metadata:
        last_updated: '2023-11-16T10:18:22.006933'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.006933'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:22.006933'
    version: '1.0'
disable_url:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:22.006933'
      version: '1.0'
    url:
      ? ''
      : default_value
      example: https://www.example.com/filter/1.txt
      metadata:
        last_updated: '2023-11-16T10:18:22.006933'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.006933'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:22.006933'
    version: '1.0'
enable_url:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:22.006933'
      version: '1.0'
    url:
      ? ''
      : default_value
      example: https://www.example.com/filter/1.txt
      metadata:
        last_updated: '2023-11-16T10:18:22.006933'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.006933'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:22.006933'
    version: '1.0'
metadata:
  last_updated: '2023-11-16T10:18:22.006933'
  version: '1.0'
refresh:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    force:
      ? ''
      : default_value
      default: false
      metadata:
        last_updated: '2023-11-16T10:18:22.006933'
        version: '1.0'
      selector:
        ? ''
        : default_value
        boolean: null
        metadata:
          last_updated: '2023-11-16T10:18:22.006933'
          version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.006933'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.006933'
    version: '1.0'
remove_url:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:22.006933'
      version: '1.0'
    url:
      ? ''
      : default_value
      example: https://www.example.com/filter/1.txt
      metadata:
        last_updated: '2023-11-16T10:18:22.006933'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.006933'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:22.006933'
    version: '1.0'
