? ''
: default_value
decrease_speed:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
    percentage_step:
      ? ''
      : default_value
      advanced: true
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
      required: false
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.150279'
          version: '1.0'
        number:
          ? ''
          : default_value
          max: 100
          metadata:
            last_updated: '2023-11-16T10:18:23.150279'
            version: '1.0'
          min: 0
          unit_of_measurement: '%'
  metadata:
    last_updated: '2023-11-16T10:18:23.150279'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: fan
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
      supported_features:
      - fan.FanEntityFeature.SET_SPEED
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
increase_speed:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
    percentage_step:
      ? ''
      : default_value
      advanced: true
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
      required: false
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.150279'
          version: '1.0'
        number:
          ? ''
          : default_value
          max: 100
          metadata:
            last_updated: '2023-11-16T10:18:23.150279'
            version: '1.0'
          min: 0
          unit_of_measurement: '%'
  metadata:
    last_updated: '2023-11-16T10:18:23.150279'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: fan
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
      supported_features:
      - fan.FanEntityFeature.SET_SPEED
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
metadata:
  last_updated: '2023-11-16T10:18:23.150279'
  version: '1.0'
oscillate:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
    oscillating:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        boolean: null
        metadata:
          last_updated: '2023-11-16T10:18:23.150279'
          version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:23.150279'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: fan
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
      supported_features:
      - fan.FanEntityFeature.OSCILLATE
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
set_direction:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    direction:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.150279'
          version: '1.0'
        select:
          ? ''
          : default_value
          metadata:
            last_updated: '2023-11-16T10:18:23.150279'
            version: '1.0'
          options:
          - forward
          - reverse
          translation_key: direction
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:23.150279'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: fan
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
      supported_features:
      - fan.FanEntityFeature.DIRECTION
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
set_percentage:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
    percentage:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.150279'
          version: '1.0'
        number:
          ? ''
          : default_value
          max: 100
          metadata:
            last_updated: '2023-11-16T10:18:23.150279'
            version: '1.0'
          min: 0
          unit_of_measurement: '%'
  metadata:
    last_updated: '2023-11-16T10:18:23.150279'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: fan
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
      supported_features:
      - fan.FanEntityFeature.SET_SPEED
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
set_preset_mode:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
    preset_mode:
      ? ''
      : default_value
      example: auto
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.150279'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:23.150279'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: fan
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
      supported_features:
      - fan.FanEntityFeature.PRESET_MODE
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
toggle:
  ? ''
  : default_value
  metadata:
    last_updated: '2023-11-16T10:18:23.150279'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: fan
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
turn_off:
  ? ''
  : default_value
  metadata:
    last_updated: '2023-11-16T10:18:23.150279'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: fan
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
turn_on:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
    percentage:
      ? ''
      : default_value
      filter:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.150279'
          version: '1.0'
        supported_features:
        - fan.FanEntityFeature.SET_SPEED
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.150279'
          version: '1.0'
        number:
          ? ''
          : default_value
          max: 100
          metadata:
            last_updated: '2023-11-16T10:18:23.150279'
            version: '1.0'
          min: 0
          unit_of_measurement: '%'
    preset_mode:
      ? ''
      : default_value
      example: auto
      filter:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.150279'
          version: '1.0'
        supported_features:
        - fan.FanEntityFeature.PRESET_MODE
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.150279'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:23.150279'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: fan
      metadata:
        last_updated: '2023-11-16T10:18:23.150279'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.150279'
      version: '1.0'
