? ''
: default_value
disable_audio:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    entity_id:
      ? ''
      : default_value
      example: camera.house_front
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.149556'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.149556'
    version: '1.0'
disable_motion_recording:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    entity_id:
      ? ''
      : default_value
      example: camera.house_front
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.149556'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.149556'
    version: '1.0'
disable_recording:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    entity_id:
      ? ''
      : default_value
      example: camera.house_front
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.149556'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.149556'
    version: '1.0'
enable_audio:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    entity_id:
      ? ''
      : default_value
      example: camera.house_front
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.149556'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.149556'
    version: '1.0'
enable_motion_recording:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    entity_id:
      ? ''
      : default_value
      example: camera.house_front
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.149556'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.149556'
    version: '1.0'
enable_recording:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    entity_id:
      ? ''
      : default_value
      example: camera.house_front
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.149556'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.149556'
    version: '1.0'
goto_preset:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    entity_id:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      selector:
        ? ''
        : default_value
        entity:
          ? ''
          : default_value
          domain: camera
          integration: amcrest
          metadata:
            last_updated: '2023-11-16T10:18:22.149556'
            version: '1.0'
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.149556'
      version: '1.0'
    preset:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
        number:
          ? ''
          : default_value
          max: 1000
          metadata:
            last_updated: '2023-11-16T10:18:22.149556'
            version: '1.0'
          min: 1
  metadata:
    last_updated: '2023-11-16T10:18:22.149556'
    version: '1.0'
metadata:
  last_updated: '2023-11-16T10:18:22.149556'
  version: '1.0'
ptz_control:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    entity_id:
      ? ''
      : default_value
      example: camera.house_front
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.149556'
      version: '1.0'
    movement:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
        select:
          ? ''
          : default_value
          metadata:
            last_updated: '2023-11-16T10:18:22.149556'
            version: '1.0'
          options:
          - down
          - left
          - left_down
          - left_up
          - right
          - right_down
          - right_up
          - up
          - zoom_in
          - zoom_out
    travel_time:
      ? ''
      : default_value
      default: 0.2
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
        number:
          ? ''
          : default_value
          max: 1
          metadata:
            last_updated: '2023-11-16T10:18:22.149556'
            version: '1.0'
          min: 0
          step: 0.01
          unit_of_measurement: seconds
  metadata:
    last_updated: '2023-11-16T10:18:22.149556'
    version: '1.0'
set_color_bw:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    color_bw:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
        select:
          ? ''
          : default_value
          metadata:
            last_updated: '2023-11-16T10:18:22.149556'
            version: '1.0'
          options:
          - auto
          - bw
          - color
    entity_id:
      ? ''
      : default_value
      example: camera.house_front
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.149556'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.149556'
    version: '1.0'
start_tour:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    entity_id:
      ? ''
      : default_value
      example: camera.house_front
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.149556'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.149556'
    version: '1.0'
stop_tour:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    entity_id:
      ? ''
      : default_value
      example: camera.house_front
      metadata:
        last_updated: '2023-11-16T10:18:22.149556'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.149556'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.149556'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.149556'
    version: '1.0'
