? ''
: default_value
download_file:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    filename:
      ? ''
      : default_value
      example: my_file_name
      metadata:
        last_updated: '2023-11-16T10:18:22.772817'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.772817'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.772817'
      version: '1.0'
    overwrite:
      ? ''
      : default_value
      default: false
      metadata:
        last_updated: '2023-11-16T10:18:22.772817'
        version: '1.0'
      selector:
        ? ''
        : default_value
        boolean: null
        metadata:
          last_updated: '2023-11-16T10:18:22.772817'
          version: '1.0'
    subdir:
      ? ''
      : default_value
      example: download_dir
      metadata:
        last_updated: '2023-11-16T10:18:22.772817'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.772817'
          version: '1.0'
        text: null
    url:
      ? ''
      : default_value
      example: http://example.org/myfile
      metadata:
        last_updated: '2023-11-16T10:18:22.772817'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.772817'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:22.772817'
    version: '1.0'
metadata:
  last_updated: '2023-11-16T10:18:22.772817'
  version: '1.0'
