? ''
: default_value
metadata:
  last_updated: '2023-11-16T10:18:23.510402'
  version: '1.0'
set_vacation:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    enabled:
      ? ''
      : default_value
      default: true
      metadata:
        last_updated: '2023-11-16T10:18:23.510402'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        boolean: null
        metadata:
          last_updated: '2023-11-16T10:18:23.510402'
          version: '1.0'
    end:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.510402'
        version: '1.0'
      selector:
        ? ''
        : default_value
        date: null
        metadata:
          last_updated: '2023-11-16T10:18:23.510402'
          version: '1.0'
    message:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.510402'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.510402'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:23.510402'
      version: '1.0'
    plain_text:
      ? ''
      : default_value
      default: true
      metadata:
        last_updated: '2023-11-16T10:18:23.510402'
        version: '1.0'
      selector:
        ? ''
        : default_value
        boolean: null
        metadata:
          last_updated: '2023-11-16T10:18:23.510402'
          version: '1.0'
    restrict_contacts:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.510402'
        version: '1.0'
      selector:
        ? ''
        : default_value
        boolean: null
        metadata:
          last_updated: '2023-11-16T10:18:23.510402'
          version: '1.0'
    restrict_domain:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.510402'
        version: '1.0'
      selector:
        ? ''
        : default_value
        boolean: null
        metadata:
          last_updated: '2023-11-16T10:18:23.510402'
          version: '1.0'
    start:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.510402'
        version: '1.0'
      selector:
        ? ''
        : default_value
        date: null
        metadata:
          last_updated: '2023-11-16T10:18:23.510402'
          version: '1.0'
    title:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.510402'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.510402'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:23.510402'
    version: '1.0'
  target:
    ? ''
    : default_value
    device:
      ? ''
      : default_value
      integration: google_mail
      metadata:
        last_updated: '2023-11-16T10:18:23.510402'
        version: '1.0'
    entity:
      ? ''
      : default_value
      integration: google_mail
      metadata:
        last_updated: '2023-11-16T10:18:23.510402'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.510402'
      version: '1.0'
