? ''
: default_value
metadata:
  last_updated: '2023-11-16T10:18:22.632217'
  version: '1.0'
set_value:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    date:
      ? ''
      : default_value
      example: 2022/11/01
      metadata:
        last_updated: '2023-11-16T10:18:22.632217'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        date: null
        metadata:
          last_updated: '2023-11-16T10:18:22.632217'
          version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.632217'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.632217'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: date
      metadata:
        last_updated: '2023-11-16T10:18:22.632217'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.632217'
      version: '1.0'
