? ''
: default_value
metadata:
  last_updated: '2023-11-16T10:18:22.101299'
  version: '1.0'
send_comfort_feedback:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:22.101299'
      version: '1.0'
    name:
      ? ''
      : default_value
      example: Bedroom
      metadata:
        last_updated: '2023-11-16T10:18:22.101299'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.101299'
          version: '1.0'
        text: null
    value:
      ? ''
      : default_value
      example: bit_warm
      metadata:
        last_updated: '2023-11-16T10:18:22.101299'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.101299'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:22.101299'
    version: '1.0'
set_comfort_mode:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:22.101299'
      version: '1.0'
    name:
      ? ''
      : default_value
      example: Bedroom
      metadata:
        last_updated: '2023-11-16T10:18:22.101299'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.101299'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:22.101299'
    version: '1.0'
set_temperature_mode:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:22.101299'
      version: '1.0'
    name:
      ? ''
      : default_value
      example: Bedroom
      metadata:
        last_updated: '2023-11-16T10:18:22.101299'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.101299'
          version: '1.0'
        text: null
    value:
      ? ''
      : default_value
      example: 22
      metadata:
        last_updated: '2023-11-16T10:18:22.101299'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.101299'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:22.101299'
    version: '1.0'
