? ''
: default_value
alarm_arm_home_instant:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    code:
      ? ''
      : default_value
      example: 1234
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.960339'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: alarm_control_panel
      integration: elkm1
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
alarm_arm_night_instant:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    code:
      ? ''
      : default_value
      example: 1234
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.960339'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: alarm_control_panel
      integration: elkm1
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
alarm_arm_vacation:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    code:
      ? ''
      : default_value
      example: 1234
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.960339'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: alarm_control_panel
      integration: elkm1
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
alarm_bypass:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    code:
      ? ''
      : default_value
      example: 4242
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.960339'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: alarm_control_panel
      integration: elkm1
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
alarm_clear_bypass:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    code:
      ? ''
      : default_value
      example: 4242
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.960339'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: alarm_control_panel
      integration: elkm1
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
alarm_display_message:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    beep:
      ? ''
      : default_value
      default: 0
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      selector:
        ? ''
        : default_value
        boolean: null
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
    clear:
      ? ''
      : default_value
      default: 2
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        number:
          ? ''
          : default_value
          max: 2
          metadata:
            last_updated: '2023-11-16T10:18:22.960339'
            version: '1.0'
          min: 0
    line1:
      ? ''
      : default_value
      default: ''
      example: The answer to life.
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        text: null
    line2:
      ? ''
      : default_value
      default: ''
      example: the universe, and everything.
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
    timeout:
      ? ''
      : default_value
      default: 0
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        number:
          ? ''
          : default_value
          max: 65535
          metadata:
            last_updated: '2023-11-16T10:18:22.960339'
            version: '1.0'
          min: 0
  metadata:
    last_updated: '2023-11-16T10:18:22.960339'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: alarm_control_panel
      integration: elkm1
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
metadata:
  last_updated: '2023-11-16T10:18:22.960339'
  version: '1.0'
sensor_counter_refresh:
  ? ''
  : default_value
  metadata:
    last_updated: '2023-11-16T10:18:22.960339'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: sensor
      integration: elkm1
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
sensor_counter_set:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
    value:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        number:
          ? ''
          : default_value
          max: 65536
          metadata:
            last_updated: '2023-11-16T10:18:22.960339'
            version: '1.0'
          min: 0
  metadata:
    last_updated: '2023-11-16T10:18:22.960339'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: sensor
      integration: elkm1
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
sensor_zone_bypass:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    code:
      ? ''
      : default_value
      example: 4242
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:22.960339'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: sensor
      integration: elkm1
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
sensor_zone_trigger:
  ? ''
  : default_value
  metadata:
    last_updated: '2023-11-16T10:18:22.960339'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: sensor
      integration: elkm1
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
set_time:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
    prefix:
      ? ''
      : default_value
      example: gatehouse
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:22.960339'
    version: '1.0'
speak_phrase:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
    number:
      ? ''
      : default_value
      example: 42
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        text: null
    prefix:
      ? ''
      : default_value
      default: ''
      example: gatehouse
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:22.960339'
    version: '1.0'
speak_word:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:22.960339'
      version: '1.0'
    number:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        number:
          ? ''
          : default_value
          max: 473
          metadata:
            last_updated: '2023-11-16T10:18:22.960339'
            version: '1.0'
          min: 1
    prefix:
      ? ''
      : default_value
      default: ''
      example: gatehouse
      metadata:
        last_updated: '2023-11-16T10:18:22.960339'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.960339'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:22.960339'
    version: '1.0'
