? ''
: default_value
browse_url:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:22.366318'
      version: '1.0'
    url:
      ? ''
      : default_value
      example: https://www.home-assistant.io
      metadata:
        last_updated: '2023-11-16T10:18:22.366318'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.366318'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:22.366318'
    version: '1.0'
metadata:
  last_updated: '2023-11-16T10:18:22.366318'
  version: '1.0'
