? ''
: default_value
metadata:
  last_updated: '2023-11-16T10:18:22.366318'
  version: '1.0'
press:
  ? ''
  : default_value
  metadata:
    last_updated: '2023-11-16T10:18:22.366318'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: button
      metadata:
        last_updated: '2023-11-16T10:18:22.366318'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:22.366318'
      version: '1.0'
