? ''
: default_value
metadata:
  last_updated: '2023-11-16T10:18:23.307049'
  version: '1.0'
ptz:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:23.307049'
      version: '1.0'
    movement:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.307049'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.307049'
          version: '1.0'
        select:
          ? ''
          : default_value
          metadata:
            last_updated: '2023-11-16T10:18:23.307049'
            version: '1.0'
          options:
          - bottom_left
          - bottom_right
          - down
          - left
          - right
          - top_left
          - top_right
          - up
    travel_time:
      ? ''
      : default_value
      default: 0.125
      metadata:
        last_updated: '2023-11-16T10:18:23.307049'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.307049'
          version: '1.0'
        number:
          ? ''
          : default_value
          max: 1
          metadata:
            last_updated: '2023-11-16T10:18:23.307049'
            version: '1.0'
          min: 0
          step: 0.005
          unit_of_measurement: seconds
  metadata:
    last_updated: '2023-11-16T10:18:23.307049'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: camera
      integration: foscam
      metadata:
        last_updated: '2023-11-16T10:18:23.307049'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.307049'
      version: '1.0'
ptz_preset:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:23.307049'
      version: '1.0'
    preset_name:
      ? ''
      : default_value
      example: TopMost
      metadata:
        last_updated: '2023-11-16T10:18:23.307049'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.307049'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:23.307049'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: camera
      integration: foscam
      metadata:
        last_updated: '2023-11-16T10:18:23.307049'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.307049'
      version: '1.0'
