? ''
: default_value
metadata:
  last_updated: '2023-11-16T10:18:23.416439'
  version: '1.0'
set_switch_override:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    duration:
      ? ''
      : default_value
      example: '{"minutes": 135}'
      metadata:
        last_updated: '2023-11-16T10:18:23.416439'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.416439'
          version: '1.0'
        object: null
    metadata:
      last_updated: '2023-11-16T10:18:23.416439'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:23.416439'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: switch
      integration: geniushub
      metadata:
        last_updated: '2023-11-16T10:18:23.416439'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.416439'
      version: '1.0'
set_zone_mode:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    entity_id:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.416439'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        entity:
          ? ''
          : default_value
          domain: climate
          integration: geniushub
          metadata:
            last_updated: '2023-11-16T10:18:23.416439'
            version: '1.0'
        metadata:
          last_updated: '2023-11-16T10:18:23.416439'
          version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.416439'
      version: '1.0'
    mode:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.416439'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.416439'
          version: '1.0'
        select:
          ? ''
          : default_value
          metadata:
            last_updated: '2023-11-16T10:18:23.416439'
            version: '1.0'
          options:
          - footprint
          - 'off'
          - timer
  metadata:
    last_updated: '2023-11-16T10:18:23.416439'
    version: '1.0'
set_zone_override:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    duration:
      ? ''
      : default_value
      example: '{"minutes": 135}'
      metadata:
        last_updated: '2023-11-16T10:18:23.416439'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.416439'
          version: '1.0'
        object: null
    entity_id:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.416439'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        entity:
          ? ''
          : default_value
          domain: climate
          integration: geniushub
          metadata:
            last_updated: '2023-11-16T10:18:23.416439'
            version: '1.0'
        metadata:
          last_updated: '2023-11-16T10:18:23.416439'
          version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.416439'
      version: '1.0'
    temperature:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.416439'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.416439'
          version: '1.0'
        number:
          ? ''
          : default_value
          max: 28
          metadata:
            last_updated: '2023-11-16T10:18:23.416439'
            version: '1.0'
          min: 4
          step: 0.1
          unit_of_measurement: "\u63B3"
  metadata:
    last_updated: '2023-11-16T10:18:23.416439'
    version: '1.0'
