? ''
: default_value
cleanup:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    device_id:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.353939'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        device:
          ? ''
          : default_value
          entity:
            ? ''
            : default_value
            device_class: connectivity
            metadata:
              last_updated: '2023-11-16T10:18:23.353939'
              version: '1.0'
          integration: fritz
          metadata:
            last_updated: '2023-11-16T10:18:23.353939'
            version: '1.0'
        metadata:
          last_updated: '2023-11-16T10:18:23.353939'
          version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.353939'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:23.353939'
    version: '1.0'
metadata:
  last_updated: '2023-11-16T10:18:23.353939'
  version: '1.0'
reboot:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    device_id:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.353939'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        device:
          ? ''
          : default_value
          entity:
            ? ''
            : default_value
            device_class: connectivity
            metadata:
              last_updated: '2023-11-16T10:18:23.353939'
              version: '1.0'
          integration: fritz
          metadata:
            last_updated: '2023-11-16T10:18:23.353939'
            version: '1.0'
        metadata:
          last_updated: '2023-11-16T10:18:23.353939'
          version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.353939'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:23.353939'
    version: '1.0'
reconnect:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    device_id:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.353939'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        device:
          ? ''
          : default_value
          entity:
            ? ''
            : default_value
            device_class: connectivity
            metadata:
              last_updated: '2023-11-16T10:18:23.353939'
              version: '1.0'
          integration: fritz
          metadata:
            last_updated: '2023-11-16T10:18:23.353939'
            version: '1.0'
        metadata:
          last_updated: '2023-11-16T10:18:23.353939'
          version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.353939'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:23.353939'
    version: '1.0'
set_guest_wifi_password:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    device_id:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.353939'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        device:
          ? ''
          : default_value
          entity:
            ? ''
            : default_value
            device_class: connectivity
            metadata:
              last_updated: '2023-11-16T10:18:23.353939'
              version: '1.0'
          integration: fritz
          metadata:
            last_updated: '2023-11-16T10:18:23.353939'
            version: '1.0'
        metadata:
          last_updated: '2023-11-16T10:18:23.353939'
          version: '1.0'
    length:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.353939'
        version: '1.0'
      required: false
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.353939'
          version: '1.0'
        number:
          ? ''
          : default_value
          max: 63
          metadata:
            last_updated: '2023-11-16T10:18:23.353939'
            version: '1.0'
          min: 8
    metadata:
      last_updated: '2023-11-16T10:18:23.353939'
      version: '1.0'
    password:
      ? ''
      : default_value
      metadata:
        last_updated: '2023-11-16T10:18:23.353939'
        version: '1.0'
      required: false
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.353939'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:23.353939'
    version: '1.0'
