? ''
: default_value
metadata:
  last_updated: '2023-11-16T10:18:22.757219'
  version: '1.0'
order:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    metadata:
      last_updated: '2023-11-16T10:18:22.757219'
      version: '1.0'
    order_entity_id:
      ? ''
      : default_value
      example: dominos.medium_pan
      metadata:
        last_updated: '2023-11-16T10:18:22.757219'
        version: '1.0'
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:22.757219'
          version: '1.0'
        text: null
  metadata:
    last_updated: '2023-11-16T10:18:22.757219'
    version: '1.0'
