? ''
: default_value
metadata:
  last_updated: '2023-11-16T10:18:23.036759'
  version: '1.0'
select_cmode:
  ? ''
  : default_value
  fields:
    ? ''
    : default_value
    cmode:
      ? ''
      : default_value
      example: cinema
      metadata:
        last_updated: '2023-11-16T10:18:23.036759'
        version: '1.0'
      required: true
      selector:
        ? ''
        : default_value
        metadata:
          last_updated: '2023-11-16T10:18:23.036759'
          version: '1.0'
        text: null
    metadata:
      last_updated: '2023-11-16T10:18:23.036759'
      version: '1.0'
  metadata:
    last_updated: '2023-11-16T10:18:23.036759'
    version: '1.0'
  target:
    ? ''
    : default_value
    entity:
      ? ''
      : default_value
      domain: media_player
      integration: epson
      metadata:
        last_updated: '2023-11-16T10:18:23.036759'
        version: '1.0'
    metadata:
      last_updated: '2023-11-16T10:18:23.036759'
      version: '1.0'
